syntax on

set tabstop=4
set softtabstop=4
set shiftwidth=4
set textwidth=79
set fileformat=unix
set expandtab
set autoindent

au! BufNewFile,BufReadPost *.{yaml,yml} set filetype=yaml foldmethod=indent
autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab
